# Change these first
owner: chriswdixon # Your GitHub username
repo: upptime-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: LeftLane.IO
    url: https://leftlane.io
  - name: 3dvirtualtoursaustin
    url: https://3dvirtualtoursaustin.com
  - name: efrensanchez.com
    url: https://efrensanchez.com
  - name: EPIC Project Management
    url: https://www.epicpmgroup.com
  - name: fridaysoutside.com
    url: https://fridaysoutside.com
  - name: Housegals.com
    url: https://housegals.com
  - name: Human Bonding Foundation
    url: https://humanbonding.org
  - name: Hutto Infinity Athletics
    url: https://huttoinfinityathletics.com
  - name: Jackson, Sjoberg LLP
    url: https://jacksonsjoberg.com
  - name: Kahanak Master Builder
    url: https://kahanek.net
  - name: Pflugerville Tours
    url: https://pflugervilletours.com
  - name: Remembering Ryan Sheehan
    url: https://www.rememberingryansheehan.com
  - name: SOS Austin
    url: https://sos-austin.org
  - name: Stars Vipers
    url: https://starsvipers.com
  - name: True A Med Spa
    url: https://trueamedspa.com
  - name: TX BMX Hall of Fame
    url: https://txbmxhof.org
  - name: TX CPA Consulting
    url: https://txcpaconsulting.com
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: upptime.leftlane.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a LIVE status page for LeftLane.IO Portfolio Sites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
